#############  Keyboard settings  ################
repeat_rate=60
repeat_delay=200
numlockon=0
xkb_rules_layout=br
xkb_rules_variant=abnt2
##################################################

#############  Monitor settings  #################
monitorrule=name:DP-1,width:1920,height:1080,refresh:165,x:0,y:0,scale:1.0,vrr:1
##################################################

#############  Animations settings  ##############
source=./Animations.conf              
##################################################


##################  Keybinds  ####################
source=./Keybinds.conf
##################################################


#############  Monitors settings  ################
source=./Monitors.conf
##################################################


##############  General settings  ################
source=./General.conf
##################################################


##############  Autostart on boot  ###############
source=./Autostart.conf
##################################################


################ Blur settings  ##################
source=./Blur.conf
##################################################


##############  Scroller settings  ###############
source=./Scroller_layout.conf
##################################################


############  Window n Layer rules  ##############
source=./Rules.conf
##################################################


###########  Environment variables  ##############
source=./Environments.conf
##################################################

##################  Tagrules  ####################
source=./Tagrules.conf
##################################################

################  Master-Stack  ##################
source=./Master-Stack.conf
##################################################

##################  Shadows  #####################
source=./Shadows.conf
##################################################
